/* AUTO-GENERATED by scripts/gen-demo-data.ts — jangan edit manual.
 *
 * Sumber: crawl nyata konten.com 2026-09-22T23:41:06.102Z (45 campaign tersedia,
 * 20 dipakai di sini). Berisi brief_detail asli: materi, narasi, CTA,
 * elemen wajib, do & don't, target audiens.
 *
 * Jalankan ulang: bun scripts/crawl-campaigns.ts && bun scripts/gen-demo-data.ts
 */
import type { RawCampaign } from "./lib/konten";

export const DEMO_CAPTURED_AT = "2026-09-22T23:41:06.102Z";

export const DEMO_CAMPAIGNS: RawCampaign[] = [
  {
    "id": "camp-1789551169226-ff8egj",
    "slug": "ibu-bagaimana-aku-tanpamu-trailer-soundtrack-film-copy",
    "title": "IBU, Bagaimana aku Tanpamu Reaksi dan Testimoni Special Screening",
    "brand": "Falcon Pictures",
    "category": "Entertainment",
    "platform": [
      "tiktok",
      "instagram"
    ],
    "status": "active",
    "campaign_type": "cpm",
    "rate_per_million": 2000,
    "cpm_tiktok": 2000,
    "cpm_instagram": 2000,
    "cpm_youtube": null,
    "budget": 190000000,
    "spent": 131853864,
    "clippers": 11988,
    "min_views": 10000,
    "min_video_duration": 10,
    "max_videos_per_clipper": null,
    "deadline": null,
    "hashtags": [
      "IBUBagaimanaAkuTanpamu",
      "reaksinonton",
      "perjuanganibu",
      "ktnfcib3"
    ],
    "tier_access": "public",
    "brief_detail": {
      "cta": "Nonton “IBU, Bagaimana aku Tanpamu 24 September di bioskop!\"",
      "materi": [
        {
          "title": "Reaksi ARTIS",
          "url": "https://drive.google.com/drive/folders/1kMdPSHEYcn_JTc-OSf6zydpqhfjEN0Mc"
        },
        {
          "title": "Nobar Yatim",
          "url": "https://drive.google.com/drive/folders/1-8fl_SdadOEj5CZxdTPnriTqPoLe255p"
        },
        {
          "title": "Testimoni Artis",
          "url": "https://drive.google.com/drive/folders/1CmhNfQwTHIu6-XnXABuPFwdaLyjJyQDn?usp=drive_link"
        },
        {
          "title": "Refrensi Style Konten",
          "url": "https://docs.google.com/document/d/10Qfw27P6sA5milcRVAaiieS5mwmX3ig6O5xrOYVptBo/edit?usp=sharing"
        },
        {
          "title": "Trailer Full",
          "url": "https://drive.google.com/drive/folders/1_4wR3yqHq7tTdmU1om76kcWRtC7BMcYs?usp=drive_link"
        },
        {
          "title": "Trailer Artis",
          "url": "https://drive.google.com/drive/folders/10ZqEoCe-NkWAfSmN3HsjJqMy_yIGAzF6?usp=drive_link"
        },
        {
          "title": "Materi Lengkap",
          "url": "https://drive.google.com/drive/folders/1Ttf80KlRH5GlmUM3BSsq9qEX-f1UU55D?usp=drive_link"
        },
        {
          "title": "Backsound Anggis",
          "url": "https://vt.tiktok.com/ZS9SwYCRvBT68-H23n9/"
        }
      ],
      "narasi": "- Reaksi atau testimoni yang mengharukan dan sedih ketika menonton film\n- Kamu bisa gunakan reaksi/testimoni artis dari Special Screening seperti “Ayu TIng-Ting, JKT48, Ivan Gunawan, Marsha Timothy, Praz Teguh, ” untuk memperkuat narasi atau artis lainnya!",
      "caption": "",
      "captionWajib": "Kamu bisa menggunakan caption dengan hook yang bikin terharu dan berikan ajakan untuk nonton bersama keluarga dan mengenai tanggal tayang IBU, Bagaimana aku Tanpamu 24 September di bioskop!",
      "hashtags": [
        "IBUBagaimanaAkuTanpamu",
        "reaksinonton",
        "perjuanganibu",
        "ktnfcib3"
      ],
      "durasiMin": "10",
      "durasiMax": "120",
      "judulFile": "IBU, Bagaimana aku Tanpamu” Reaksi dan Testimoni Special Screening",
      "elemenWajib": "- Gunakan reaksi atau testimoni artis dari Special Screening atau reaksi penonton \n- Boleh gunakan footage diluar materi dengan syarat harus Artis yang ada direaksi. Contohnya: Menggunakan Footage Ayu ting-ting bersama Bilqis (anaknya) lalu disambungkan ke reaksi\n- Boleh gunakan Trailer salah satu atau boleh di mixing dari 4 trailer FIlm “IBU, Bagaimana aku Tanpamu”\n- Setiap akhir video WAJIB ada keterangan film tayang 24 September di Bioskop gunakan Bumper Ending atau Poster yang sudah disediakan\n- Pastikan durasi clip atau hook diluar materi tidak sampai 60% dari durasi video\n- Backsound Anggis - Tiktok: https://vt.tiktok.com/ZS9SwYCRvBT68-H23n9/",
      "contohVideo": [],
      "tujuanCampaign": "Brand awareness: orang tahu brand/konten",
      "targetAudiens": "Semua Umur",
      "instruksiBrief": "",
      "bolehDilakukan": [
        "- Kamu diperbolehkan ambil hook atau footage diluar materi dengan syarat footage tersebut merupakan artis dari pemain film tersebut (Anggis, Devaki, Praz Teguh, Ivan Gunawan, Marsha Timothy, Sara Wija",
        "- Boleh gunakan footage diluar materi dengan syarat harus Artis yang ada direaksi. Contohnya: Menggunakan Footage Ayu ting-ting bersama Bilqis (anaknya)",
        "- Kombinasikan footage nobar anak yatim, testimoni artis & keseruan Gala",
        "- Poster pada ending video"
      ],
      "dilarangDilakukan": [
        "- DILARANG Menggunakan hook diluar materi perjuangan seorang ibu dan diluar pemain atau artis reaksi.",
        "- Dilarang konten SARA",
        "- Dilarang Menjatuhkan nama Brand",
        "- Dilarang Mention akun Falcon",
        "- Dilarang menggunakan ads ataupun bot"
      ],
      "nicheAkunDisetujui": [
        "Entertainment"
      ],
      "minimumFollowers": 0
    }
  },
  {
    "id": "camp-1788410964576-c6rf0b",
    "slug": "david-noah-copy",
    "title": "David Noah",
    "brand": "David Noah",
    "category": "Education",
    "platform": [
      "instagram",
      "youtube"
    ],
    "status": "active",
    "campaign_type": "cpm",
    "rate_per_million": 2500,
    "cpm_tiktok": null,
    "cpm_instagram": 2500,
    "cpm_youtube": 2500,
    "budget": 16666666,
    "spent": 5813321,
    "clippers": 6417,
    "min_views": 10000,
    "min_video_duration": 10,
    "max_videos_per_clipper": null,
    "deadline": null,
    "hashtags": [
      "davidnoah",
      "fortiscircle"
    ],
    "tier_access": "public",
    "brief_detail": {
      "cta": "Ajak orang untuk cek Fortis Circle",
      "materi": [
        {
          "title": "Fortis Circle",
          "url": "https://fortiscircle.id/"
        },
        {
          "title": "7 Pelajaran Bisnis dari 10 Tahun Pengalaman Gua",
          "url": "https://youtu.be/LRYZxfQXyzA?si=lZ1A8hbUjJ45n6UK"
        },
        {
          "title": "Materi siap pakai Fortis",
          "url": "https://drive.google.com/drive/folders/1-AYh4aCYuPN2ozn-uNEI_jvuNqeHIC6y"
        },
        {
          "title": "Materi 1",
          "url": "https://www.youtube.com/watch?v=lDCsFAhVUkw&t=311s&pp=ygUKZGF2aWQgbm9haA%3D%3D"
        },
        {
          "title": "Materi 2",
          "url": "https://www.youtube.com/watch?v=d1sfVRVwZ3o&pp=ygUKZGF2aWQgbm9haA%3D%3D"
        },
        {
          "title": "Materi 3",
          "url": "https://www.youtube.com/watch?v=xMOKC0VitME&t=487s&pp=ygUKZGF2aWQgbm9haNIHCQkTDAGHKiGM7w%3D%3D"
        },
        {
          "title": "Materi 4",
          "url": "https://www.youtube.com/watch?v=Unf6cWMvJv0"
        },
        {
          "title": "Materi 5",
          "url": "https://www.youtube.com/watch?v=Ky7AAz2poF4&t=2104s"
        },
        {
          "title": "From Zero to Hero 1",
          "url": "https://www.youtube.com/watch?v=kiEeW4Qd86o&t=2513s&pp=ygUKZGF2aWQgbm9haA%3D%3D"
        },
        {
          "title": "From Zero to Hero 2",
          "url": "https://www.youtube.com/watch?v=wKttHxjJNHc&t=1890s&pp=ygUKZGF2aWQgbm9haA%3D%3D"
        },
        {
          "title": "From Zero to Hero 3",
          "url": "https://www.youtube.com/watch?v=RxWxDYzxf_Y&t=30s"
        },
        {
          "title": "From Zero to Hero 4",
          "url": "https://www.youtube.com/watch?v=lX_w4ghqPsc&t=3111s&pp=ygUKZGF2aWQgbm9haA%3D%3D"
        }
      ],
      "narasi": "- Menunjukkan perjalanan dan pelajaran hidup David Noah\n- Membuat audience relate dan melihat sisi personal David di luar saham\n- Fokus kemampuan David dalam dunia saham\n- Keuntungan-keuntungan member Fortis Circle\n- Highlight Fortis Circle Community\n- Integritas dari seorang David Noah",
      "caption": "",
      "captionWajib": "-",
      "hashtags": [
        "davidnoah",
        "fortiscircle"
      ],
      "durasiMin": "30",
      "durasiMax": "90",
      "judulFile": "David Noah",
      "elemenWajib": "- Clipping sesuai dengan narasi yang disediakan dan CTA-nya\n- Highlight David Noah saat berbicara\n- Clipper harus mencantumkan  link fortiscircle.id/class di bio profile\n- Harus menambahkan logo fortis di semua video clippingan yang dibuat",
      "contohVideo": [],
      "tujuanCampaign": "Brand awareness: orang tahu brand/konten",
      "targetAudiens": "Semua Umur",
      "instruksiBrief": "",
      "bolehDilakukan": [
        "- Mengambil footage dari YouTube yang diberikan",
        "- Bisa memilih bebas section yang mau dijadikan clipping",
        "- Fokus ke highlight David Noah saat berbicara",
        "- Tambahkan logo fortis di semua video clippingan yang dibuat"
      ],
      "dilarangDilakukan": [
        "- Dilarang mengandung SARA,",
        "- Tidak ada obrolan politik, agama, seksual, atau rasial",
        "- Dilarang screenshot campaign",
        "- Dilarang menggunakan ads maupun bot",
        "- Tidak diizinkan menggunakan video yang sudah di posting sama David Noah sendiri terus di repost kembali. Diharuskan dari video editan sendiri",
        "-  Dilarang menjanjikan keuntungan, merekomendasikan saham tertentu dengan tambahan editan sendiri, harus sesuai konteks dari clippingannya"
      ],
      "nicheAkunDisetujui": [
        "Lifestyle",
        "Education"
      ],
      "minimumFollowers": 0
    }
  },
  {
    "id": "camp-1788155065927-rptafi",
    "slug": "bevan",
    "title": "Bevan Pramudito - Trader Crypto",
    "brand": "Bevan",
    "category": "Education",
    "platform": [
      "tiktok",
      "instagram"
    ],
    "status": "active",
    "campaign_type": "cpm",
    "rate_per_million": 3000,
    "cpm_tiktok": 3000,
    "cpm_instagram": 3000,
    "cpm_youtube": null,
    "budget": 10000000,
    "spent": 852377,
    "clippers": 4691,
    "min_views": 10000,
    "min_video_duration": 10,
    "max_videos_per_clipper": null,
    "deadline": null,
    "hashtags": [
      "bevanpramudito",
      "memecoin",
      "narrativelabs",
      "crypto"
    ],
    "tier_access": "public",
    "brief_detail": {
      "cta": "-",
      "materi": [
        {
          "title": "Link bio",
          "url": "https://trade.bevanpramudito.com/"
        },
        {
          "title": "Ironman Triathlon",
          "url": "https://drive.google.com/drive/folders/17spOI2GBEbuevxka4NTd5hEZz2Uq3UCL"
        },
        {
          "title": "B Roll materi",
          "url": "https://drive.google.com/drive/folders/1M5n4OrigepH1Dwl66ive-u5oZSe1CY7w"
        },
        {
          "title": "Instagram Bevan Pramudito",
          "url": "https://www.instagram.com/bevanpramudt/"
        },
        {
          "title": "X Bevan Pramudito",
          "url": "https://x.com/bevanpramudt"
        },
        {
          "title": "Youtube Bevan Pramudito (Lifestyle Trader)",
          "url": "https://www.youtube.com/@bevanpramudt"
        },
        {
          "title": "Vlog : Golf with Henky Andinata",
          "url": "https://www.youtube.com/watch?v=hxCqjBdKeqE"
        },
        {
          "title": "Podcast : Dengan Samuel Christ",
          "url": "https://www.youtube.com/watch?v=6ZCxcdstkzo"
        },
        {
          "title": "Podcast :  ASET PULUHAN MILIAR DARI DEGEN CRYPTO!",
          "url": "https://www.youtube.com/watch?v=PoHF4T6Cxcc"
        },
        {
          "title": "Podcast : Bevan Pramudito Jackpot Rp2M dari Crypto",
          "url": "https://www.youtube.com/watch?v=AOvc-ujPwWc"
        },
        {
          "title": "Podcast :  Untung Miliaran dari NFT Sebelum Lulus SMA!",
          "url": "https://www.youtube.com/watch?v=sXRR6-wOnx0"
        },
        {
          "title": "Podcast : Masih kuliah udah cuan miliaran dari memecoin?",
          "url": "https://www.youtube.com/watch?v=1VIFsPrkkK0"
        }
      ],
      "narasi": "- Bevan baru saja menyelesaikan Ironman Triathlon (Salah satu lomba paling menantang di dunia).\nBisa dijadikan clip seperti “Mahasiswa UI pertama yang menyelesaikan Ironman”, “Mahasiswa ini\nbisa menyelesaikan lomba paling ekstrim di dunia sambil trading crypto”, “Ga cuma trading,\nmahasiswa 21 tahun ini berhasil menyelesaikan lomba paling ekstrem di dunia”, dan sejenisnya",
      "caption": "",
      "captionWajib": "Bebas selama masih relevan dengan narasi",
      "hashtags": [
        "bevanpramudito",
        "memecoin",
        "narrativelabs",
        "crypto"
      ],
      "durasiMin": "15",
      "durasiMax": "120",
      "judulFile": "Bevan",
      "elemenWajib": "- Membangun image Bevan sebagai “Trader crypto muda aset ratusan miliar”, “1 Miliar\npertama di usia 17 Tahun” ilmunya mencari meme coin yang akan jadi alpha di antara ribuan\ncoin dan narrative yang ada di market. Menonjolkan pengalaman, track record, cara berpikir, serta\nmetode Wallet Tracking & Narrative Play di dunia crypto. Tonjolkan kehidupan Bevan yang\ndiinginkan oleh audience (adventure, olahraga, having fun, ketemu arti/influencer, naik private jet,\nskydiving, dll).\n- Pasang link https://trade.bevanpramudito.com/ di bio",
      "contohVideo": [],
      "tujuanCampaign": "Brand awareness: orang tahu brand/konten",
      "targetAudiens": "Semua Umur",
      "instruksiBrief": "",
      "bolehDilakukan": [
        "- Mengambil footage atau hook diluar materi selama masih relevan",
        "- Bisa memilih bebas section yang mau dijadikan clipping",
        "- Konten harus terlihat orisinal, autentik, dan menunjukkan proses (genuine)",
        "- Gunakan materi baru vlog bulanan, YouTube, shorts, update harian, tutorial, podcast clips, b-roll lifestyle",
        "- Masukan link di bio profile akun"
      ],
      "dilarangDilakukan": [
        "- Dilarang menjatuhkan siapapun",
        "- Dilarang menjanjikan keuntungan, merekomendasikan saham/coin tertentu dengan tambahan editan sendiri harus sesuai konteks dari clipping-nya",
        "- Dilarang konten flexing pamer harta/uang tunai secara berlebihan",
        "- Dilarang mengandung SARA",
        "- Tidak ada obrolan politik, agama, seksual, atau rasial",
        "- Dilarang screenshot campaign",
        "- Dilarang menggunakan ads maupun bot",
        "- DILARANG menggunakan AI/Opus Clip editing software"
      ],
      "nicheAkunDisetujui": [
        "Education"
      ],
      "minimumFollowers": 0
    }
  },
  {
    "id": "camp-1790052986576-jtuafa",
    "slug": "podcast-wondermoms-community-vol-2-copy",
    "title": "Sasa MAKTERCHEF",
    "brand": "ARO Creative",
    "category": "Lifestyle",
    "platform": [
      "tiktok",
      "instagram"
    ],
    "status": "active",
    "campaign_type": "cpm",
    "rate_per_million": 3000,
    "cpm_tiktok": null,
    "cpm_instagram": null,
    "cpm_youtube": null,
    "budget": 4000000,
    "spent": 0,
    "clippers": 49,
    "min_views": 10000,
    "min_video_duration": 10,
    "max_videos_per_clipper": null,
    "deadline": null,
    "hashtags": [
      "SasaMelezatkan",
      "sasa",
      "makterchefsasa"
    ],
    "tier_access": "public",
    "brief_detail": {
      "cta": "Tidak ada",
      "materi": [
        {
          "title": "CHAOS! The Moms' First Cooking Action in the MakterChef Kitchen | MAKTERCHEF EPI",
          "url": "https://www.youtube.com/watch?v=wne3Rkr2LA0"
        },
        {
          "title": "THE DECISION! Whose Dish Impressed the Judges the Most? | MAKTERCHEF EPISODE 2",
          "url": "https://www.youtube.com/watch?v=tqBTGfh-ePo"
        }
      ],
      "narasi": "- Mendistribusikan dan mempromosikan konten Sasa",
      "caption": "",
      "captionWajib": "Tidak ada",
      "hashtags": [
        "SasaMelezatkan",
        "sasa",
        "makterchefsasa"
      ],
      "durasiMin": "10",
      "durasiMax": "60",
      "judulFile": "Sasa",
      "elemenWajib": "Tidak ada",
      "contohVideo": [],
      "tujuanCampaign": "Brand awareness: orang tahu brand/konten",
      "targetAudiens": "18–24, 25–34, 35–44, 45+",
      "instruksiBrief": "",
      "bolehDilakukan": [
        "- Bisa mengambil footage yang diberikan diatas",
        "- Boleh menggunakan hook diluar materi asal tidak hoax, miss leading"
      ],
      "dilarangDilakukan": [
        "Dilarang konten SARA, Agama dan Gender",
        "Dilarang menjelekkan pihak lain termasuk brand wondermoms",
        "Dilarang memberikan image yang jelek terhadap wanita",
        "Dilarang memakai ads dan bot"
      ],
      "nicheAkunDisetujui": [
        "Lifestyle",
        "Education"
      ],
      "minimumFollowers": 0
    }
  },
  {
    "id": "camp-1789984304240-v476bm",
    "slug": "growlab-beyond-the-podcast-1",
    "title": "Growlab Beyond The Podcast #1",
    "brand": "Growlab Digital Solution",
    "category": "Lifestyle",
    "platform": [
      "tiktok",
      "instagram"
    ],
    "status": "active",
    "campaign_type": "cpm",
    "rate_per_million": 3000,
    "cpm_tiktok": 3000,
    "cpm_instagram": 3000,
    "cpm_youtube": null,
    "budget": 28750000,
    "spent": 0,
    "clippers": 160,
    "min_views": 5000,
    "min_video_duration": 10,
    "max_videos_per_clipper": null,
    "deadline": null,
    "hashtags": [
      "growlabid",
      "growlabofficial",
      "podcastgrowlab",
      "growlabinsight",
      "jasaoptimasigrowlab"
    ],
    "tier_access": "public",
    "brief_detail": {
      "cta": "Mau tahu insight lebih banyak soal seller e-commerce? Yuk tonton full podcast Growtalk di Youtube sekarang.",
      "materi": [
        {
          "title": "Logo",
          "url": "https://drive.google.com/drive/folders/1MA0axsEhRSo4_SnIQP9bBsrM_qIiyfoi"
        },
        {
          "title": "Youtube Growlab Official",
          "url": "https://www.youtube.com/@Growlab-Official"
        },
        {
          "title": "GROWTALK #12 | Bisnis Online Bukan Mati Karena Sepi: Ini Kesalahan Seller yang S",
          "url": "https://www.youtube.com/watch?v=E-FG4GbFd7A"
        },
        {
          "title": "Iklan Shopee Jalan Tapi Order Nol? Cara Memperbaiki Urutan Iklan yang Benar untu",
          "url": "https://www.youtube.com/watch?v=wOcqXpbktxw"
        },
        {
          "title": "Iklan Shopee Makin Mahal Tapi Sales Segitu-Gitu Aja? Ini Penyebabnya | Bedah Das",
          "url": "https://www.youtube.com/watch?v=RTKOJcWDw8w"
        },
        {
          "title": "Jangan Asal Pasang Iklan! Gak Bisa Hitung ROAS Bisa Bahaya Buat Toko | Bedah Das",
          "url": "https://www.youtube.com/watch?v=UiYQLiFwsnM&t=5s"
        },
        {
          "title": "Omset 100 Juta Tapi Rekening Kosong? Ini yang Salah dari Cara Kamu Hitung Untung",
          "url": "https://www.youtube.com/watch?v=uEAs09jOkDM"
        }
      ],
      "narasi": "- Growlab membahas insight seputar marketplace, bisnis, dan growth.\n- Setiap clip harus memberikan insight/value yang jelas kepada penonton.\n- Buat penonton penasaran dengan pembahasan lengkapnya.\n- Arahkan penonton untuk melanjutkan ke full episode di YouTube Growlab.",
      "caption": "",
      "captionWajib": "[hook bisa disesuaikan dengan isi clip]\n\nKalau kamu setuju atau nggak?\n\nPembahasan lengkapnya ada di podcast Growlab.\n\n🎧 Full episode → YouTube Growlab",
      "hashtags": [
        "growlabid",
        "growlabofficial",
        "podcastgrowlab",
        "growlabinsight",
        "jasaoptimasigrowlab"
      ],
      "durasiMin": "15",
      "durasiMax": "60",
      "judulFile": "Growlab Beyond The Podcast #1",
      "elemenWajib": "- “Ternyata, omzet tinggi belum tentu bisnis kamu sehat.”\n- “Ini alasan kenapa toko lo rame tapi duitnya nggak kerasa.”\n- “Ternyata ada alasan kenapa toko ini tiba-tiba berhenti growth.”",
      "contohVideo": [],
      "tujuanCampaign": "",
      "targetAudiens": "",
      "instruksiBrief": "",
      "bolehDilakukan": [
        "- Pastikan clip punya konteks yang cukup untuk dipahami penonton.",
        "- Cantumkan branding Growlab.",
        "- Buat caption yang memancing curiosity dan engagement."
      ],
      "dilarangDilakukan": [
        "- Jangan gunakan opening yang lambat atau terlalu banyak basa-basi",
        "- Jangan menggunakan animasi sebagai hook",
        "- Tidak diperkenankan untuk kisi klip dengan video yang lain",
        "- Jangan membuat clickbait yang tidak sesuai isi.",
        "- Jangan menggunakan subtitle yang terlalu kecil/sulit dibaca.",
        "- Jangan menambahkan visual/effect yang mengganggu isi pembicaraan.",
        "- Jangan upload konten duplikat/spam hanya untuk mengejar views.",
        "- Memakai bot dan ads"
      ],
      "nicheAkunDisetujui": [],
      "minimumFollowers": 0
    }
  },
  {
    "id": "camp-1789981900895-09x0el",
    "slug": "owner-artha-ldt",
    "title": "Novelia Indriyati Hasanah (Artha LDT)",
    "brand": "Artha ldt",
    "category": "Lifestyle",
    "platform": [
      "tiktok"
    ],
    "status": "active",
    "campaign_type": "cpm",
    "rate_per_million": 5000,
    "cpm_tiktok": 5000,
    "cpm_instagram": null,
    "cpm_youtube": null,
    "budget": 5000000,
    "spent": 0,
    "clippers": 139,
    "min_views": 10000,
    "min_video_duration": 10,
    "max_videos_per_clipper": null,
    "deadline": null,
    "hashtags": [
      "arthaldt",
      "arthaldtbpom",
      "produkviral",
      "ownerarthaldt",
      "ownerteroyal"
    ],
    "tier_access": "public",
    "brief_detail": {
      "cta": "-",
      "materi": [
        {
          "title": "BRIEF CONTOH CLIPER",
          "url": "https://cdn.konten.com/materi/e8b663ee-bd3d-45b0-8113-a7b8fbc8081d/1789981147047-67d91945.mp4"
        },
        {
          "title": "MATERI VIDIO CLIPER",
          "url": "https://drive.google.com/drive/folders/1ttOYknrKYiiE-UxNglObMaMW6Pz6LUun?usp=drive_link"
        }
      ],
      "narasi": "- Menunjukkan perjalanan dan pelajaran hidup Novelia sebagai pemilik artha dan pemilik pabrik IBR\n- Membuat audience relate dan melihat sisi personal Novelia",
      "caption": "",
      "captionWajib": "Pengusaha muda sejawa timur",
      "hashtags": [
        "arthaldt",
        "arthaldtbpom",
        "produkviral",
        "ownerarthaldt",
        "ownerteroyal"
      ],
      "durasiMin": "-",
      "durasiMax": "-",
      "judulFile": "DIBALIK SUKSESNYA OWNER ARTHA",
      "elemenWajib": "- Di awal kasi tulisan \"Dulu pernikahan mereka nggak direstui kedua orang tua,,,sekarang justru jadi pasangan pengusaha sukses\"\n- Mohon menggunakan sound yg ada di contoh materi",
      "contohVideo": [],
      "tujuanCampaign": "",
      "targetAudiens": "",
      "instruksiBrief": "",
      "bolehDilakukan": [
        "- Mengambil footage dari materi yang diberikan",
        "- Bisa memilih bebas section yang mau dijadikan clipping"
      ],
      "dilarangDilakukan": [
        "- Dilarang mengandung SARA,",
        "- Tidak ada obrolan politik, agama, seksual, atau rasial",
        "- Dilarang screenshot campaign",
        "- Dilarang menggunakan ads maupun bot"
      ],
      "nicheAkunDisetujui": [],
      "minimumFollowers": 0
    }
  },
  {
    "id": "camp-1787110822676-g8w3i5",
    "slug": "gapura-sariwangi",
    "title": "SariWangi Gapura Competition 17an",
    "brand": "Sariwangi",
    "category": "Lifestyle",
    "platform": [
      "tiktok",
      "instagram"
    ],
    "status": "active",
    "campaign_type": "cpm",
    "rate_per_million": 3000,
    "cpm_tiktok": 3000,
    "cpm_instagram": null,
    "cpm_youtube": null,
    "budget": 44901000,
    "spent": 2136519,
    "clippers": 6807,
    "min_views": 50000,
    "min_video_duration": 10,
    "max_videos_per_clipper": null,
    "deadline": null,
    "hashtags": [
      "WaktunyaNgetehIndonesia",
      "GapuraSariWangi",
      "DirgahayuIndonesia",
      "SariWangi"
    ],
    "tier_access": "public",
    "brief_detail": {
      "cta": "Mengajak masyarakat untuk memeriahkan sekaligus memberikan apresiasi terhadap program SariWangi yang mendukung Hari Kemerdekaan",
      "materi": [
        {
          "title": "Materi 1",
          "url": "https://vt.tiktok.com/ZSVM7wbCc/"
        },
        {
          "title": "Materi 2",
          "url": "https://vt.tiktok.com/ZSVMvsU3v/"
        },
        {
          "title": "Materi 3",
          "url": "https://vt.tiktok.com/ZSVMvqXxQ/"
        },
        {
          "title": "Materi 4",
          "url": "https://vt.tiktok.com/ZSVMvaVrp/"
        },
        {
          "title": "Materi 5",
          "url": "https://vt.tiktok.com/ZSVMvCKo7/"
        },
        {
          "title": "Materi 6",
          "url": "https://vt.tiktok.com/ZSVM39GCt/"
        }
      ],
      "narasi": "SariWangi mendukung acara 17-an warga di berbagai daerah di Indonesia",
      "caption": "",
      "captionWajib": "Gunakan hashtag wajib dan tag @sariwangi_id",
      "hashtags": [
        "WaktunyaNgetehIndonesia",
        "GapuraSariWangi",
        "DirgahayuIndonesia",
        "SariWangi"
      ],
      "durasiMin": "15",
      "durasiMax": "60",
      "judulFile": "SariWangi Gapura Competition 17an",
      "elemenWajib": "- Logo SariWangi/Savoria dan elemen #WaktunyaNgetehIndonesia terlihat jelas\n- Tunjukkan gapura hasil hias warga & keseruan games bersama SariWangi\n- Wajib pakai seluruh material yang disertakan\n- Logo SariWangi/Savoria dan elemen #WaktunyaNgetehIndonesia terlihat jelas; tunjukkan gapura hasil hias warga & keseruan games bersama SariWangi",
      "contohVideo": [],
      "tujuanCampaign": "Brand awareness: orang tahu brand/konten",
      "targetAudiens": "Semua Umur",
      "instruksiBrief": "",
      "bolehDilakukan": [
        "- Menampilkan proses & hasil hias gapura",
        "- Menampilkan keseruan warga bermain games bersama SariWang"
      ],
      "dilarangDilakukan": [
        "- Dilarang menyinggung isu politik/SARA/boikot",
        "- Dilarang merusak atau memodifikasi logo SariWangi/Savoria",
        "- Dilarang screenshot campaign",
        "- Dilarang menggunakan ads maupun bo"
      ],
      "nicheAkunDisetujui": [
        "Lifestyle"
      ],
      "minimumFollowers": 0
    }
  },
  {
    "id": "camp-1787045098223-210eg6",
    "slug": "mykonos-parfum",
    "title": "Mykonos Parfum",
    "brand": "Mykonos",
    "category": "Lifestyle",
    "platform": [
      "tiktok",
      "instagram"
    ],
    "status": "active",
    "campaign_type": "cpm",
    "rate_per_million": 4000,
    "cpm_tiktok": 4000,
    "cpm_instagram": null,
    "cpm_youtube": null,
    "budget": 5562500,
    "spent": 4962531,
    "clippers": 2495,
    "min_views": 5000,
    "min_video_duration": 10,
    "max_videos_per_clipper": null,
    "deadline": null,
    "hashtags": [
      "MykonosParfumBaru",
      "Mykonos"
    ],
    "tier_access": "public",
    "brief_detail": {
      "cta": "Ajak audience menebak parfum apa yang bakal dirilis oleh Mykonos",
      "materi": [
        {
          "title": "Video materi",
          "url": "https://vt.tiktok.com/ZSVr3JYqc/"
        },
        {
          "title": "Refrensi video",
          "url": "https://vt.tiktok.com/ZSVrwFQ8H/"
        },
        {
          "title": "Refrensi materi 2",
          "url": "https://vt.tiktok.com/ZSVBrX6T7/"
        },
        {
          "title": "Refrensi materi 3",
          "url": "https://vt.tiktok.com/ZSVBhRbV2/"
        }
      ],
      "narasi": "- Ajak audience menebak parfum apa yang bakal dirilis oleh Mykonos dengan memakai video Banghalim sebagai hook",
      "caption": "",
      "captionWajib": "Cek website https://officialmykonos.com/",
      "hashtags": [
        "MykonosParfumBaru",
        "Mykonos"
      ],
      "durasiMin": "-",
      "durasiMax": "-",
      "judulFile": "Mykonos",
      "elemenWajib": "- Lalu JJ ke parfum tebakan mereka — bebas mau tebak parfum baru, atau parfum lama tapi ada ukuran 100ml-nya\n- Botol parfum boleh dibikin pakai AI, sesuai kreasi clipper — yang penting wajib banget nebak\n- Clipper wajib banget nebak / menebak parfum",
      "contohVideo": [],
      "tujuanCampaign": "Brand awareness: orang tahu brand/konten",
      "targetAudiens": "Semua Umur",
      "instruksiBrief": "",
      "bolehDilakukan": [
        "- Buat konten yang sesuai dengan gaya masing-masing creator",
        "- Boleh menggunakan trending audio"
      ],
      "dilarangDilakukan": [
        "- Dilarang mengandung unsur politik, SARA, pornografi, atau konten yang melanggar hukum",
        "- Tidak menyinggung, menyebut, atau menyindir pihak lain",
        "- Dilarang screenshot campaign",
        "- Dilarang menggunakan ads maupun bot"
      ],
      "nicheAkunDisetujui": [
        "Lifestyle"
      ],
      "minimumFollowers": 0
    }
  },
  {
    "id": "camp-1787110674549-muwkre",
    "slug": "sariwangi-dvc",
    "title": "SariWangi - Waktunya Ngeteh Indonesia (DVC)",
    "brand": "Sariwangi",
    "category": "Lifestyle",
    "platform": [
      "tiktok",
      "instagram",
      "youtube"
    ],
    "status": "active",
    "campaign_type": "cpm",
    "rate_per_million": 3000,
    "cpm_tiktok": 3000,
    "cpm_instagram": null,
    "cpm_youtube": null,
    "budget": 44901000,
    "spent": 0,
    "clippers": 1673,
    "min_views": 50000,
    "min_video_duration": 10,
    "max_videos_per_clipper": null,
    "deadline": null,
    "hashtags": [
      "WaktunyaNgetehIndonesia",
      "SariWangi",
      "DirgahayuIndonesia"
    ],
    "tier_access": "public",
    "brief_detail": {
      "cta": "Memeriahkan dan memberi pujian program SariWangi yang mendukung dan merayakan Hari Kemerdekaan bersama warga",
      "materi": [
        {
          "title": "Materi",
          "url": "https://drive.google.com/file/d/1MK-PhMx_ggCysnCH5Y8CoUVdrvgGpEth/view?usp=drivesdk"
        }
      ],
      "narasi": "SariWangi mendukung acara 17-an warga di berbagai daerah di Indonesia",
      "caption": "",
      "captionWajib": "Sertakan hashtag wajib dan tag @sariwangi_id di setiap postingan",
      "hashtags": [
        "WaktunyaNgetehIndonesia",
        "SariWangi",
        "DirgahayuIndonesia"
      ],
      "durasiMin": "15",
      "durasiMax": "60",
      "judulFile": "SariWangi – Waktunya Ngeteh Indonesia (DVC)",
      "elemenWajib": "- Logo SariWangi muncul jelas pada detik 0–3 dan di akhir video\n- Gunakan cuplikan resmi DVC SariWangi\n- Wajib pakai seluruh material yang disertakan",
      "contohVideo": [],
      "tujuanCampaign": "Brand awareness: orang tahu brand/konten",
      "targetAudiens": "25–34",
      "instruksiBrief": "",
      "bolehDilakukan": [
        "- Menampilkan keberagaman budaya & daerah di Indonesia",
        "- Menampilkan momen kebersamaan/kekeluargaan",
        "- Menggunakan cuplikan resmi DVC SariWangi"
      ],
      "dilarangDilakukan": [
        "- Dilarang mengandung unsur politik, SARA, pornografi, atau konten yang melanggar hukum",
        "- Tidak menyinggung, menyebut, atau menyindir pihak lain",
        "- Dilarang screenshot campaign",
        "- Dilarang menggunakan ads maupun bot"
      ],
      "nicheAkunDisetujui": [
        "Lifestyle"
      ],
      "minimumFollowers": 0
    }
  },
  {
    "id": "camp-1786943484855-on8vn1",
    "slug": "shinzui-sunscreen",
    "title": "Shinzui Sunscreen",
    "brand": "Shinzui",
    "category": "Entertainment",
    "platform": [
      "tiktok"
    ],
    "status": "active",
    "campaign_type": "cpm",
    "rate_per_million": 3000,
    "cpm_tiktok": 3000,
    "cpm_instagram": null,
    "cpm_youtube": null,
    "budget": 24109999,
    "spent": 0,
    "clippers": 1073,
    "min_views": 20000,
    "min_video_duration": 10,
    "max_videos_per_clipper": null,
    "deadline": null,
    "hashtags": [
      "Shinzui",
      "ShinzuiWhitessentials",
      "SunscreenGlowing"
    ],
    "tier_access": "public",
    "brief_detail": {
      "cta": "Buktiin sendiri, sunscreen doang bisa glowing!",
      "materi": [
        {
          "title": "Materi 1",
          "url": "https://www.tiktok.com/@fujiiian/video/7587028407884500242?is_from_webapp=1&sender_device=pcsha"
        },
        {
          "title": "Materi 2",
          "url": "https://www.tiktok.com/@rtsfya/video/7602619461140581639?lang=en"
        },
        {
          "title": "Materi 3",
          "url": "https://www.instagram.com/reels/DPYqyPRgEV4/"
        },
        {
          "title": "Meteri 4",
          "url": "https://www.instagram.com/reels/DQ6LAufEp82/"
        },
        {
          "title": "Foto produk",
          "url": "https://drive.google.com/file/d/13ELZW0JUNa7Zo3jq2adeb922NH68SMpW/view?usp=sharing"
        },
        {
          "title": "Materi tambahan",
          "url": "https://docs.google.com/document/d/1-YIJ-enhAZhWQYscIj_o-a2MEld6xVJWGCAUDAqX16g/edit?usp=sharing"
        }
      ],
      "narasi": "- Sun safe glow: melindungi kulit dari sinar UV sekaligus memberikan efek glowing\n- Cukup 1 jari untuk 1x pemakaian",
      "caption": "",
      "captionWajib": "0",
      "hashtags": [
        "Shinzui",
        "ShinzuiWhitessentials",
        "SunscreenGlowing"
      ],
      "durasiMin": "10",
      "durasiMax": "60",
      "judulFile": "Shinzui Sunscreen",
      "elemenWajib": "- Hook curiosity di 3 detik pertama\n- Reveal \"ternyata cuma sunscreen\" setelah hook\n- Produk Shinzui Sunscreen terlihat jelas\n- Menunjukkan hasil glowing di wajah\n- Reveal \"glowingnya ternyata cuma dari sunscreen\" setelah hook",
      "contohVideo": [],
      "tujuanCampaign": "Brand awareness: orang tahu brand/konten",
      "targetAudiens": "Semua Umur",
      "instruksiBrief": "",
      "bolehDilakukan": [
        "- Produk jelas terlihat di video",
        "- Highlight key benefits: instant glow, pemakaian cukup 1 jari",
        "- Konten fun, relatable, mancing penasaran",
        "- Fokus ke hook yang bikin orang berhenti scroll"
      ],
      "dilarangDilakukan": [
        "- Konten mengandung SARA atau topik sensitif lainnya yang dapat merusak citra brand",
        "- Produk yang kurang jelas/minim berada di video",
        "- Video gelap, low-quality, atau background buram yang mengganggu visibility produk",
        "- Jangan buka video pakai klaim teknis",
        "- Dilarang screenshot campaign",
        "- Dilarang menggunakan ads maupun bo"
      ],
      "nicheAkunDisetujui": [
        "Lifestyle"
      ],
      "minimumFollowers": 0
    }
  },
  {
    "id": "camp-1789377174333-5zromb",
    "slug": "emina-fresh-drop-tint-2",
    "title": "Emina Fresh Drop Tint",
    "brand": "Emina",
    "category": "Lifestyle",
    "platform": [
      "tiktok",
      "instagram",
      "youtube"
    ],
    "status": "active",
    "campaign_type": "cpm",
    "rate_per_million": 3000,
    "cpm_tiktok": 3000,
    "cpm_instagram": 3000,
    "cpm_youtube": 3000,
    "budget": 30000000,
    "spent": 0,
    "clippers": 212,
    "min_views": 20000,
    "min_video_duration": 10,
    "max_videos_per_clipper": null,
    "deadline": null,
    "hashtags": [
      "Emina",
      "EminaFreshdroptint"
    ],
    "tier_access": "public",
    "brief_detail": {
      "cta": "Ajak untuk coba Emina Fresh Drop Tint",
      "materi": [
        {
          "title": "Inka materi 1",
          "url": "https://www.tiktok.com/@inkathhh/video/7671627754827238676?is_from_webapp=1&sender_device=pc&web_id=7648817630790288912"
        },
        {
          "title": "Sybil materi 1",
          "url": "https://www.tiktok.com/@andrepanaga/video/7673863428850699541?is_from_webapp=1&sender_device=pc&web_id=7672659312455616017"
        },
        {
          "title": "Syibil Materi 2",
          "url": "https://drive.google.com/file/d/16vgjjZQZQTFL9wQ_BVlz3LzbZVjdRod1/view"
        },
        {
          "title": "Syibil Materi 3",
          "url": "https://www.instagram.com/reel/Db0A8apSs5d/?igsi=MWtqb3QxM2V2Mzhjdg=="
        },
        {
          "title": "Miskah Materi 1",
          "url": "https://drive.google.com/file/d/1oyXqyK3OU15kbNNfTiOkQZ-kZTAbNFpz/view?usp=sharing"
        },
        {
          "title": "Abel materi 1",
          "url": "https://drive.google.com/file/d/1trYfrcnXzqjN6NMkVoFKA3QexqLtYn6r/view?usp=sharing"
        },
        {
          "title": "Materi tambahan",
          "url": "https://drive.google.com/drive/folders/1d1R29PTD83Lnv9qoRbiFfFpg7qReBMTU?usp=sharing"
        }
      ],
      "narasi": "- Clipping sesuai dengan narasi dan highlight masing-masing KOL (lihat panduan per KOL di bawah)",
      "caption": "",
      "captionWajib": "-",
      "hashtags": [
        "Emina",
        "EminaFreshdroptint"
      ],
      "durasiMin": "10",
      "durasiMax": "120",
      "judulFile": "Emina Fresh Drop Tint",
      "elemenWajib": "-",
      "contohVideo": [],
      "tujuanCampaign": "",
      "targetAudiens": "",
      "instruksiBrief": "",
      "bolehDilakukan": [
        "- Tone dibuat softsell dan jangan branded",
        "- Text hook/supers harus conversational",
        "- Satu footage bisa dieksplor menjadi beberapa angle/hook berbeda",
        "- Boleh combine dengan footage KOL lainnya"
      ],
      "dilarangDilakukan": [
        "- Jangan hanya upload full video tanpa additional context",
        "- Jangan overclaim hasil produk",
        "- Jangan membuat narasi seolah KOL mengatakan sesuatu yang sebenarnya tidak dia katakan",
        "- Dilarang screenshot campaign"
      ],
      "nicheAkunDisetujui": [],
      "minimumFollowers": 0
    }
  },
  {
    "id": "camp-1789380984283-m8gd8z",
    "slug": "free-fire-x-naruto-shippuden",
    "title": "Free Fire x Naruto Shippuden",
    "brand": "Garena",
    "category": "Gaming",
    "platform": [
      "tiktok",
      "instagram"
    ],
    "status": "active",
    "campaign_type": "cpm",
    "rate_per_million": 7000,
    "cpm_tiktok": 7000,
    "cpm_instagram": 7000,
    "cpm_youtube": null,
    "budget": 18500000,
    "spent": 7330697,
    "clippers": 1468,
    "min_views": 10000,
    "min_video_duration": 10,
    "max_videos_per_clipper": null,
    "deadline": null,
    "hashtags": [
      "NinjaBooyah",
      "FreeFire",
      "FFxNaruto"
    ],
    "tier_access": "public",
    "brief_detail": {
      "cta": "Dapatkan Bundle Hinata Gratis dari Event Free Fire x Naruto Shippuden",
      "materi": [
        {
          "title": "Content Promotion 1",
          "url": "https://www.tiktok.com/@freefirebgid/video/7683901109458439444"
        },
        {
          "title": "Content Promotion 2",
          "url": "https://www.instagram.com/p/DdDdfFqDQMT/?img_index=1"
        },
        {
          "title": "Content Promotion 3",
          "url": "https://www.instagram.com/p/DdEIaA5ieVv/"
        },
        {
          "title": "Jot Marapthon",
          "url": "https://www.tiktok.com/@tierisonn/video/7685754815867047186?lang=en"
        },
        {
          "title": "Ridoodiri",
          "url": "https://www.tiktok.com/@ridoodiri/video/7686072612379692308"
        },
        {
          "title": "Materi tambahan",
          "url": "https://drive.google.com/drive/folders/1L0keYcU6O1yftEteEwmA2penguDnpcHP"
        }
      ],
      "narasi": "- Gameplay Clip\n- Dapatkan Bundle Hinata Gratis\n- Bundle Naruto, Sasuke, Sakura, Kakashi, dan Jiraiya kembali\n- Konten Gameplay Free Fire (Jedag Jedug ala TikTok) asalkan menggunakan Bundle Naruto\n- Konten yang menunjukkan dengan Ninjutsu, Skill Naruto di Game Free Fire\n\nContent Creator Clip\n- Ambil konten yang berisikan informasi penting terkait kolaborasi Free Fire x Naruto Shippuden\n- Ambil momen lucu atau menarik dari Content Creator",
      "caption": "",
      "captionWajib": "Kalian bisa dapetin Bundle Hinata GRATIS di Free Fire! Ayo login dan main sekarang",
      "hashtags": [
        "NinjaBooyah",
        "FreeFire",
        "FFxNaruto"
      ],
      "durasiMin": "30",
      "durasiMax": "60",
      "judulFile": "Free fire X  Naruto",
      "elemenWajib": "Penjelasan terkait kolaborasi Free Fire x Naruto Shippuden",
      "contohVideo": [],
      "tujuanCampaign": "",
      "targetAudiens": "",
      "instruksiBrief": "",
      "bolehDilakukan": [
        "- Wajib menjelaskan konten kolaborasi Free Fire x Naruto Shippuden",
        "- Wajib menyebarkan informasi Bundle Hinata Gratis di Event Free Fire x Naruto Shippuden",
        "- Boleh membuat konten sendiri dengan style Jedag-Jedug TikTok, namun Wajib menggunakan Bundle kolaborasi Free Fire x Naruto Shippuden"
      ],
      "dilarangDilakukan": [
        "- Apabila Footage atau asset yang digunakan tidak HD",
        "- Footage atau asset yang digunakan membuat brand \"Free Fire\" & \"Naruto Shippuden\" terlihat negative",
        "- Tidak boleh menggunakan kata-kata SARA",
        "- Tidak boleh mencuri konten sesama clippers",
        "- Tidak view botting, ataupun bayar views",
        "- Tidak boleh membandingkan atau memasukkan brand lain di dalam konten"
      ],
      "nicheAkunDisetujui": [],
      "minimumFollowers": 0
    }
  },
  {
    "id": "camp-1789800123405-hf9dnf",
    "slug": "bigbang-jakarta-sold-out-copy",
    "title": "BIGBANG Jakarta Sold Out (Instagram)",
    "brand": "PK Entertainment",
    "category": "Entertainment",
    "platform": [
      "instagram"
    ],
    "status": "active",
    "campaign_type": "cpm",
    "rate_per_million": 3000,
    "cpm_tiktok": null,
    "cpm_instagram": null,
    "cpm_youtube": null,
    "budget": 4500000,
    "spent": 52119,
    "clippers": 184,
    "min_views": 10000,
    "min_video_duration": 10,
    "max_videos_per_clipper": null,
    "deadline": null,
    "hashtags": [],
    "tier_access": "public",
    "brief_detail": {
      "cta": "Ajak siap-siap war tiket di semua tahap penjualan berikutnya",
      "materi": [
        {
          "title": "Web presale",
          "url": "http://bigbanginjakarta.com/"
        },
        {
          "title": "Seatmap, VIP benefit & presale guide",
          "url": "https://www.instagram.com/p/DckPTHtmX40/?igsi=MWMxbGpyaGV4NjZnOQ=="
        },
        {
          "title": "BIGBANG concert",
          "url": "https://ygfamily.com/en/artists/bigbang/concert"
        }
      ],
      "narasi": "- Penjualan BIGBANG V.I.P Membership Presale di Indonesia sold out kurang dari 1 jam!\n- Siap-siap war tiket di semua tahap penjualan karena BIGBANG V.I.P Membership Presale aja udah sold out ga sampe 1 jam",
      "caption": "",
      "captionWajib": "Cantumkan Ticket Sales dates presale dan seatmap yang ada",
      "hashtags": [],
      "durasiMin": "15",
      "durasiMax": "60",
      "judulFile": "BIGBANG Jakarta Phase 2",
      "elemenWajib": "- Sold-out concert Singapore BIGBANG sold out di Singapore kurang dari 1  jam.\n- G-Dragon world tour (2025–26) Momentum terbaru",
      "contohVideo": [],
      "tujuanCampaign": "Brand awareness: orang tahu brand/konten",
      "targetAudiens": "18–24, 25–34, 35–44",
      "instruksiBrief": "",
      "bolehDilakukan": [
        "- Fokus ke BIGBANG & keseruan war tiket secara umum",
        "- Nostalgia boleh ditambahkan sebagai narasi ke konser & war tiket",
        "- Pakai footage & aset resmi sesuai guardrail",
        "- Detail brief dijaga rahasia"
      ],
      "dilarangDilakukan": [
        "- Jangan bahas kompetitor, artis, atau konser lain sama sekali",
        "- Jangan ungkit drama / kepergian member lama (Fokus ke hype konser, musik, dan legacy panggung.)",
        "- Tanpa rumor / bocoran (seat plan, harga) sebelum resmi",
        "- Tanpa endorse / ajakan calo & jual-beli tiket",
        "- Tanpa SARA / rasisme, seksual, kontroversi, politik",
        "- Dilarang menggunakan ads maupun bot",
        "- Dilarang screenshot campaign"
      ],
      "nicheAkunDisetujui": [
        "Entertainment"
      ],
      "minimumFollowers": 0
    }
  },
  {
    "id": "camp-1789023996556-80gamb",
    "slug": "english-is-easy",
    "title": "English is Easy",
    "brand": "English is Easy",
    "category": "Education",
    "platform": [
      "tiktok",
      "instagram",
      "youtube"
    ],
    "status": "active",
    "campaign_type": "cpm",
    "rate_per_million": 2000,
    "cpm_tiktok": 2000,
    "cpm_instagram": 2000,
    "cpm_youtube": 2000,
    "budget": 25000000,
    "spent": 0,
    "clippers": 235,
    "min_views": 10000,
    "min_video_duration": 10,
    "max_videos_per_clipper": null,
    "deadline": null,
    "hashtags": [
      "englishiseasy",
      "lesbahasainggris",
      "english",
      "ECCT25"
    ],
    "tier_access": "public",
    "brief_detail": {
      "cta": "Coba TRIAL GRATISnya di Link in BIO",
      "materi": [
        {
          "title": "Website English is easy",
          "url": "https://englishiseasy.com/"
        },
        {
          "title": "Link kelas Trial Gratis di bio akun",
          "url": "https://englishiseasy.com/auth/register?ref=book"
        },
        {
          "title": "Dilan",
          "url": "https://drive.google.com/drive/folders/13qgAGQmbECnSXK3TqQZ-oCd6-4dIw9iW?usp=sharing"
        },
        {
          "title": "Ivan Gunawan",
          "url": "https://drive.google.com/drive/folders/1R9Egf6B9uuQ_TAEYpl9OahwLkyyFwvpA?usp=sharing"
        },
        {
          "title": "Mongol",
          "url": "https://drive.google.com/drive/folders/1GD7vmsqgdbMBlxbW2u88WNWDdfJQJ01a?usp=sharing"
        },
        {
          "title": "Sara",
          "url": "https://drive.google.com/drive/folders/1jlEcETy5FuyRYZE9clJiMcyoY7ZpDofo?usp=sharing"
        },
        {
          "title": "KOL",
          "url": "https://drive.google.com/drive/folders/1UNNdvIjtM9RQndOCwIse0rJ1joOEHttb?usp=sharing"
        },
        {
          "title": "Materi lengkap",
          "url": "https://drive.google.com/drive/folders/1y9a73kM24s3Y6N4YVoijI8avH2bgdVYf?usp=sharing"
        },
        {
          "title": "Informasi tambahan tentang English is easy",
          "url": "https://kontendotcom.b-cdn.net/public/materi-img/72ff3ac9-cb95-48e8-b5c6-6a9ea2c44860/1789023349522-2a45b135.pdf"
        }
      ],
      "narasi": "- DIJAMIN PEDE bicara Bahasa Inggris dalam 3 bulan kalau belum PEDE, dapat kelas lanjutan GRATIS\n- Metode yang bikin berani ngomong, bukan hafal grammar yang ribet\n- Pakai pola kalimat dari Bahasa Indonesia & penjalasannya dalam Bahasa Indonesia di tahap awal jadi mudah & cepat dipahami.\n- Maksimal 4 siswa dalam 1 kelas, jadi gak ada rasa minder & pasti dapat bagian ngomong\n- Kursus untuk semua usia dan level, mulai dari 6 tahun. (Anak-anak, Remaja, Dewasa) Kurikulum & Kelas disesuaiakan dengan usia dan kemampuan murid. Belajar dari nol sampai PEDE ngomong.",
      "caption": "",
      "captionWajib": "Bebas asal relevan dengan isi konten.",
      "hashtags": [
        "englishiseasy",
        "lesbahasainggris",
        "english",
        "ECCT25"
      ],
      "durasiMin": "30",
      "durasiMax": "120",
      "judulFile": "English is Easy",
      "elemenWajib": "- Pakai materi yang ada sesuai dengan narasi\n- Pasang link berikut di BIO kamu https://englishiseasy.com/auth/register?ref=book",
      "contohVideo": [],
      "tujuanCampaign": "Brand awareness: orang tahu brand/konten",
      "targetAudiens": "18–24",
      "instruksiBrief": "",
      "bolehDilakukan": [
        "- Gunakan Hook atau Footage diluar Materi diperbolehkan asal relevan"
      ],
      "dilarangDilakukan": [
        "- Jangan menghubungkan brand dengan foto, orang, atau isu yang kontroversial/sensitif (SARA, politik, seksual, kekerasan)",
        "- Jangan mengejek orang yang tidak bisa Bahasa Inggris",
        "- Jangan menambah janji sendiri — harga, diskon, \"fasih 1 bulan\", dan sejenisnya",
        "- Jangan memotong kutipan artis sampai maknanya berubah",
        "- Jangan menjelekkan kursus lain atau menyebut kompetitor",
        "- Dilarang view botting, bayar views, atau re-upload tanpa editing",
        "- Dilarang screenshot campaign"
      ],
      "nicheAkunDisetujui": [
        "Lifestyle"
      ],
      "minimumFollowers": 0
    }
  },
  {
    "id": "camp-1785051884227-wz1549",
    "slug": "wardah-color-circuit",
    "title": "Wardah Color Circuit",
    "brand": "wardah",
    "category": "Entertainment",
    "platform": [
      "tiktok",
      "instagram",
      "youtube"
    ],
    "status": "active",
    "campaign_type": "cpm",
    "rate_per_million": 3000,
    "cpm_tiktok": null,
    "cpm_instagram": null,
    "cpm_youtube": null,
    "budget": 20000000,
    "spent": 2687258,
    "clippers": 9899,
    "min_views": 15000,
    "min_video_duration": 10,
    "max_videos_per_clipper": null,
    "deadline": null,
    "hashtags": [
      "WardahColourCircuit",
      "WardahColourCircuit2026",
      "WardahEventBlokM",
      "WardahEvent"
    ],
    "tier_access": "public",
    "brief_detail": {
      "cta": "Dateng ke Wardah Colour Circuit, Nirmana Falatehan — sebelum 9 Agustus!",
      "materi": [
        {
          "title": "Gubernur Blok M",
          "url": "https://drive.google.com/drive/folders/120lbmsApOONFJJ7QPlvU2B_-WquABqqj?usp=sharing"
        },
        {
          "title": "Venue",
          "url": "https://drive.google.com/drive/folders/1A7zZw2Rywpy3N11DSOEP-P6qRYzZkHYa?usp=drive_link"
        },
        {
          "title": "Amma",
          "url": "https://drive.google.com/drive/folders/1lCnBUiZG17x5tcQ1sfx0ntBo-0zor3aQ?usp=sharing"
        },
        {
          "title": "Michelle",
          "url": "https://drive.google.com/drive/folders/1s71ZjGCrDNMU5obPeBoQxRmJBzEEnN6Q?usp=drive_link"
        },
        {
          "title": "Sashfir",
          "url": "https://drive.google.com/drive/folders/1lt2RNj4z5LhvPP-8jqdSYkVWPXg1H9cq?usp=sharing"
        },
        {
          "title": "Experience (Yola)",
          "url": "https://drive.google.com/drive/folders/13hAwICO-yZE1OZQeG74v4KAsv-HqsjBA?usp=drive_link"
        },
        {
          "title": "Endurance",
          "url": "https://drive.google.com/drive/folders/11WuhC4tJoHhUrPqzZcXRnLCM4Y2-75Se?usp=drive_link"
        },
        {
          "title": "Exploration",
          "url": "https://drive.google.com/drive/folders/1UESImDO675S0Xi6FvkAzSkELW9wEZ0jh?usp=drive_link"
        },
        {
          "title": "Product",
          "url": "https://drive.google.com/drive/folders/1eZzTYjj7kIXIYgY9dzo4ztNv4AKdsjGM?usp=drive_link"
        },
        {
          "title": "Tambahan Materi: Instagram Wardah Beauty",
          "url": "https://www.instagram.com/wardahbeauty/"
        },
        {
          "title": "Tambahan Materi: Wardah Colour Circuit",
          "url": "https://www.instagram.com/wardahcolourcircuit/"
        }
      ],
      "narasi": "1. Colour Circuit = cara paling gampang tau personal colour kamu\n2. Lokasi: Nirmana Falatehan Lt. 1, Blok M — cuma sampai 9 Agustus 2026\n3. Banyak zona seru: Beauty Pit Stop, race simulator, photo studio, cafe & merch\n4. Precision Lab (analisis personal + makeup class) = berbayar & wajib reservasi",
      "caption": "",
      "captionWajib": "Wardah Colour Circuit — Nirmana Falatehan Lt. 1, Blok M. Sampai 9 Agustus 2026.",
      "hashtags": [
        "WardahColourCircuit",
        "WardahColourCircuit2026",
        "WardahEventBlokM",
        "WardahEvent"
      ],
      "durasiMin": "10",
      "durasiMax": "60",
      "judulFile": "Wardah Colorfit",
      "elemenWajib": "- Nama event + lokasi + tanggal muncul minimal 1x (caption/overlay). \n- Sebut \"sampai 9 Agustus\" sebagai pengingat waktu. \n- Kalau bahas Precision Lab, sebut wajib reservasi.",
      "contohVideo": [],
      "tujuanCampaign": "Brand awareness: orang tahu brand/konten",
      "targetAudiens": "18–24, 25–34",
      "instruksiBrief": "",
      "bolehDilakukan": [
        "- Konten reaksi & experience: hasil colour analysis, race simulator, photo studio, cafe & merch",
        "- Ajak teman/rombongan, tunjukkan cara ke lokasi (MRT Blok M) & suasana ramainya",
        "- Sebut zona berbayar dengan jujur (Precision Lab: reservasi)"
      ],
      "dilarangDilakukan": [
        "- Isu SARA/politik/kontroversi — jaga citra Wardah (brand halal & santun)",
        "- Klaim semua gratis, Precision Lab berbayar; jangan sebut info harga/promo yang belum dikonfirmasi",
        "- Klaim skincare/medis berlebihan; nyenggol brand lain",
        "- Screenshot campaign"
      ],
      "nicheAkunDisetujui": [
        "Entertainment",
        "Lifestyle",
        "Education"
      ],
      "minimumFollowers": 10
    }
  },
  {
    "id": "camp-1787833793458-mc4rg7",
    "slug": "cara-progress-lebih-cepat-dari-99-orang",
    "title": "Cara Progress Lebih Cepat dari 99% Orang",
    "brand": "Suli",
    "category": "Education",
    "platform": [
      "instagram"
    ],
    "status": "active",
    "campaign_type": "cpm",
    "rate_per_million": 5000,
    "cpm_tiktok": null,
    "cpm_instagram": null,
    "cpm_youtube": null,
    "budget": 5000000,
    "spent": 74732,
    "clippers": 50,
    "min_views": 10000,
    "min_video_duration": 10,
    "max_videos_per_clipper": null,
    "deadline": null,
    "hashtags": [
      "suliantoindriaputra"
    ],
    "tier_access": "exclusive",
    "brief_detail": {
      "cta": "Follow @suliantoindriaputra",
      "materi": [
        {
          "title": "Link YouTube",
          "url": "https://youtu.be/4-LUaK_RNvw"
        }
      ],
      "narasi": "- Edukasi, bukan entertainment.",
      "caption": "",
      "captionWajib": "Follow @suliantoindriaputra",
      "hashtags": [
        "suliantoindriaputra"
      ],
      "durasiMin": "20",
      "durasiMax": "90",
      "judulFile": "Cara Progress Lebih Cepat dari 99% Orang",
      "elemenWajib": "Tidak ada",
      "contohVideo": [],
      "tujuanCampaign": "Education: orang paham produk / topik",
      "targetAudiens": "18–24, 25–34",
      "instruksiBrief": "",
      "bolehDilakukan": [
        "Boleh memotong beberapa bagian dari video untuk membuat alur lebih padat.",
        "Boleh menambahkan zoom in/out sederhana.",
        "Boleh menambahkan B-roll yang relevan.",
        "Boleh menggunakan sound effect ringan.",
        "Boleh menggunakan background music selama suara utama tetap jelas.",
        "Boleh mengubah opening menjadi bagian paling menarik dari pembicaraan.",
        "Boleh menambahkan headline atau text hook di awal.",
        "Boleh membuat judul clip berbeda selama tidak mengubah makna.",
        "Boleh menggunakan format storytelling, list, atau satu statement kuat.",
        "Boleh membuat beberapa clip dari angle berbeda dari video yang sama."
      ],
      "dilarangDilakukan": [
        "Tidak boleh mengubah konteks sehingga speaker terlihat mengatakan sesuatu yang berbeda.",
        "Tidak boleh menggunakan clickbait yang bertentangan dengan isi video.",
        "Tidak boleh memotong kalimat dengan cara yang mengubah kesimpulan.",
        "Tidak boleh menambahkan klaim finansial yang tidak disebutkan di video.",
        "Tidak boleh memasukkan unsur SARA, pornografi, perjudian, atau konten ilegal.",
        "Tidak boleh menyerang individu atau kelompok tertentu.",
        "Tidak boleh menggunakan watermark akun lain.",
        "Tidak boleh menutupi wajah speaker dengan elemen editing berlebihan.",
        "Tidak boleh membuat clip yang hanya berisi motivasi tanpa insight atau takeaway yang jelas."
      ],
      "nicheAkunDisetujui": [
        "Education"
      ],
      "minimumFollowers": 10
    }
  },
  {
    "id": "camp-1787800926868-mxqjrm",
    "slug": "monster-hunter-outlanders",
    "title": "Monster Hunter Outlanders.",
    "brand": "Garena",
    "category": "Gaming",
    "platform": [
      "tiktok",
      "instagram",
      "youtube"
    ],
    "status": "active",
    "campaign_type": "cpm",
    "rate_per_million": 5000,
    "cpm_tiktok": 5000,
    "cpm_instagram": null,
    "cpm_youtube": null,
    "budget": 20000000,
    "spent": 4177120,
    "clippers": 2735,
    "min_views": 10000,
    "min_video_duration": 10,
    "max_videos_per_clipper": null,
    "deadline": null,
    "hashtags": [
      "mhocbt"
    ],
    "tier_access": "public",
    "brief_detail": {
      "cta": "Pre register Monster Hunter Outlanders di Google Play Store atau Apple App Store sekarang",
      "materi": [
        {
          "title": "Materi 1",
          "url": "https://www.youtube.com/watch?v=mp_2CA0wk6U&t=11s"
        },
        {
          "title": "Materi 2",
          "url": "https://www.youtube.com/watch?v=4mZhmj9eu9k"
        }
      ],
      "narasi": "Buat clip video Monster Hunter Outlanders sekreatif mungkin dari sumber konten yang disediakan",
      "caption": "",
      "captionWajib": "-",
      "hashtags": [
        "mhocbt"
      ],
      "durasiMin": "30",
      "durasiMax": "90",
      "judulFile": "Monster Hunter Outlanders.",
      "elemenWajib": "- 70% dari seluruh konten wajib melampirkan video gameplay\n- Hook awal wajib yang engaging dari yang dilakukan oleh creator/content yang di clip\n- Dilarang mengclip full muka creator — gameplay Monster Hunter Outlanders wajib lebih dominan",
      "contohVideo": [],
      "tujuanCampaign": "Brand awareness: orang tahu brand/konten",
      "targetAudiens": "Semua Umur",
      "instruksiBrief": "",
      "bolehDilakukan": [
        "- Membuat clip dari konten yang disediakan dan mengeditnya untuk menjadi lebih engaging dan berpotensi FYP",
        "- Buat konten terlihat lucu, menyenangkan, dan pesan CTA tersampaikan"
      ],
      "dilarangDilakukan": [
        "- Dilarang menggunakan kata \"autentik\"",
        "- Dilarang mengandung SARA, menghina game lain, membahas bug dalam game, melanggar peraturan negara Indonesia",
        "- Tidak ada obrolan politik, agama, seksual, atau rasial",
        "- Dilarang screenshot campaign",
        "- Dilarang menggunakan ads maupun bot"
      ],
      "nicheAkunDisetujui": [
        "Gaming",
        "Entertainment"
      ],
      "minimumFollowers": 0
    }
  },
  {
    "id": "camp-1783176479621-fse061",
    "slug": "tehpucuk-harum-less-sugar",
    "title": "TehPucuk Harum Less Sugar",
    "brand": "Teh Pucuk",
    "category": "Entertainment",
    "platform": [
      "tiktok",
      "instagram"
    ],
    "status": "active",
    "campaign_type": "cpm",
    "rate_per_million": 3000,
    "cpm_tiktok": null,
    "cpm_instagram": null,
    "cpm_youtube": null,
    "budget": 50000000,
    "spent": 7422069,
    "clippers": 15519,
    "min_views": 10000,
    "min_video_duration": 10,
    "max_videos_per_clipper": null,
    "deadline": null,
    "hashtags": [
      "tehpucukharum",
      "tehpucukharumlesssugar",
      "lesssugar"
    ],
    "tier_access": "public",
    "brief_detail": {
      "cta": "Opsional",
      "materi": [
        {
          "title": "Contoh Komunikasi Teh Pucuk Less Sugar.pdf",
          "url": "https://auth.konten.com/storage/v1/object/public/materi/00b8eef2-07cf-4be7-a85b-f9ce168c8014/1783177539930-e0f8f95a.pdf"
        },
        {
          "title": "Nana Andrew",
          "url": "https://drive.google.com/drive/folders/15_qy1_CaxGlrWLpg2uVEvVoBr-mPaHaN?usp=sharing"
        },
        {
          "title": "Angle Konten Teh Pucuk Less Sugar.pdf",
          "url": "https://auth.konten.com/storage/v1/object/public/materi/00b8eef2-07cf-4be7-a85b-f9ce168c8014/1783177574755-a2d83c68.pdf"
        },
        {
          "title": "Rekomendasi Materi Teh Pucuk Less Sugar.pdf",
          "url": "https://auth.konten.com/storage/v1/object/public/materi/00b8eef2-07cf-4be7-a85b-f9ce168c8014/1783178046627-a5647aab.pdf"
        },
        {
          "title": "Video Sal Priadi",
          "url": "https://drive.google.com/drive/folders/191mRdp9JBXvAA8XJaCZAsqNzMoKCalli?usp=drive_link"
        },
        {
          "title": "Materi tambahan",
          "url": "https://drive.google.com/drive/folders/1Tjy8ahPlWEz58nxGBWJuOBEvQgWgd-jF"
        }
      ],
      "narasi": "- PRODUK — Teh Pucuk sekarang punya varian Less Sugar, kemasan botol, masih baru.\n- RASA — gulanya dikurangin, tapi tetep nikmat & seger.\n- BEDA — ga pait. Less sugar lain biasanya pait/hambar, yang ini enggak.",
      "caption": "",
      "captionWajib": "Tidak ada",
      "hashtags": [
        "tehpucukharum",
        "tehpucukharumlesssugar",
        "lesssugar"
      ],
      "durasiMin": "10",
      "durasiMax": "180",
      "judulFile": "Teh Pucuk Harum Less Sugar",
      "elemenWajib": "Direkomendasikan menggunakan muka Aldi Taher agar video nge-hook.\n\n- Footage Aldi Taher: Potong momen paling lucu/relatable, tambahin caption soal rasa.\n- Footage The Dudas: Ambil bagian yang seru, arahin ke pesan \"ga pait, tetep seger\".",
      "contohVideo": [],
      "tujuanCampaign": "Brand awareness: orang tahu brand/konten",
      "targetAudiens": "Semua Umur",
      "instruksiBrief": "",
      "bolehDilakukan": [
        "- Fokus ke rasa: rendah gula tapi enak, ga pait.",
        "- Sebut jelas variannya: Teh Pucuk Harum Less Sugar (kemasan botol).",
        "- Pakai/potong footage talent yang udah disediain.",
        "- Bikin konten yang natural, kayak obrolan sehari-hari.",
        "- Ganti-ganti gaya video biar ga bosenin — ada 8 angle bisa dipilih."
      ],
      "dilarangDilakukan": [
        "- ⚠️ PENTING: DILARANG KERAS MENAMPILKAN FOTO ATAU FOOTAGE RAFFI AHMAD",
        "- Jangan sebut atau bandingin merek pesaing langsung — cukup bilang \"less sugar biasanya...\" secara umum.",
        "- Jangan lebay soal kesehatan. Dilarang bilang \"bikin kurus\", \"bikin sehat\", \"kayak obat\". Cukup \"rendah gula\".",
        "- Jangan bikin kutipan/klaim palsu atas nama talent.",
        "- No SARA, politik, konten seksual."
      ],
      "nicheAkunDisetujui": [
        "Entertainment",
        "Lifestyle",
        "Education"
      ],
      "minimumFollowers": 10
    }
  },
  {
    "id": "camp-1789780995262-zqa2g9",
    "slug": "davidwijaya23-x-fyp-media",
    "title": "David Wijaya x FYP Media",
    "brand": "FYP Media",
    "category": "Education",
    "platform": [
      "tiktok",
      "instagram",
      "youtube"
    ],
    "status": "active",
    "campaign_type": "cpm",
    "rate_per_million": 2500,
    "cpm_tiktok": 2500,
    "cpm_instagram": 2500,
    "cpm_youtube": 2500,
    "budget": 3000000,
    "spent": 0,
    "clippers": 48,
    "min_views": 10000,
    "min_video_duration": 10,
    "max_videos_per_clipper": null,
    "deadline": null,
    "hashtags": [
      "DavidWijaya23",
      "Sesimpelini"
    ],
    "tier_access": "public",
    "brief_detail": {
      "cta": "Mencantumkan atau mengarahkan audiens ke akun social media resmi David Wijaya.",
      "materi": [
        {
          "title": "Youtube David Wijaya",
          "url": "https://www.youtube.com/@davidwijaya23"
        },
        {
          "title": "Instagram David Wijaya",
          "url": "https://www.instagram.com/davidwijaya23/"
        },
        {
          "title": "Tiktok David Wijaya",
          "url": "https://www.tiktok.com/@apt.davidwijaya"
        },
        {
          "title": "Poster (wajib)",
          "url": "https://drive.google.com/drive/folders/1oHFmOf3olxrcf0APLNw8Eklfe28vtcDY"
        }
      ],
      "narasi": "- NARASI positif yang menginspirasi anak muda untuk pintar mengelola uang. \n- Gunakan cuplikan pada podcast/sosial media yang David",
      "caption": "",
      "captionWajib": "Bebas tapi caption Wajib menceritakan profile David Wijaya beserta tips sesuai yang ada pada cuplikan video konten tersebut",
      "hashtags": [
        "DavidWijaya23",
        "Sesimpelini"
      ],
      "durasiMin": "30",
      "durasiMax": "120",
      "judulFile": "Davidwijaya23 x FYP Media",
      "elemenWajib": "Wajib tampilkan poster di materi, dapat ditaruh di akhir dengan durasi sekitar 3-5 detik",
      "contohVideo": [],
      "tujuanCampaign": "",
      "targetAudiens": "",
      "instruksiBrief": "",
      "bolehDilakukan": [
        "- Menggunakan potongan konten dari akun David Wijaya yang relevan dengan topik edukasi keuangan, investasi, bisnis, dan financial planning.",
        "- Menggunakan hook/judul/caption yang menarik selama tetap sesuai dengan konteks dan isi asli video.",
        "- Boleh menambahkan subtitle, text overlay, cut, zoom, transition, dan elemen editing lain selama tidak mengubah makna atau konteks pembicaraan.",
        "- Boleh menggunakan sound/music yang sesuai dan tidak mengganggu pesan utama konten.",
        "- Menggunakan sentimen dan framing yang positif, edukatif, informatif, dan konstruktif."
      ],
      "dilarangDilakukan": [
        "- Dilarang mengubah, memotong, atau menyusun ulang pernyataan sehingga mengubah makna atau konteks asli pembicaraan.",
        "- Dilarang membuat narasi, judul, caption, atau thumbnail yang menyesatkan, provokatif, atau memberikan kesan yang tidak sesuai dengan isi video.",
        "- Dilarang menggunakan sentimen negatif, fitnah, penghinaan, serangan personal, atau framing yang dapat merugikan reputasi David Wijaya.",
        "- Dilarang menggunakan AI untuk membuat, memodifikasi, atau memanipulasi wajah, suara, atau pernyataan David Wijaya.",
        "- Dilarang memakai bot dan ads",
        "- Dilarang mengklaim David Wijaya mengatakan atau mendukung sesuatu yang tidak terdapat dalam konten asli.",
        "- Dilarang menggunakan materi dari sumber lain atau akun lain seolah-olah merupakan pernyataan David Wijaya tanpa izin.",
        "- Dilarang menghapus konteks penting dari video yang dapat menyebabkan audiens salah memahami pesan."
      ],
      "nicheAkunDisetujui": [],
      "minimumFollowers": 0
    }
  },
  {
    "id": "camp-1784706214338-ik3fkb",
    "slug": "bodycare-artha-ldt",
    "title": "BODYCARE ARTHA LDT",
    "brand": "Artha ldt",
    "category": "Lifestyle",
    "platform": [
      "tiktok"
    ],
    "status": "active",
    "campaign_type": "cpm",
    "rate_per_million": 7000,
    "cpm_tiktok": null,
    "cpm_instagram": null,
    "cpm_youtube": null,
    "budget": 10000000,
    "spent": 3316367,
    "clippers": 9287,
    "min_views": 10000,
    "min_video_duration": 10,
    "max_videos_per_clipper": null,
    "deadline": null,
    "hashtags": [
      "arthaldt",
      "arthaldtbpom",
      "bunjiownerartha",
      "testimoniartha"
    ],
    "tier_access": "public",
    "brief_detail": {
      "cta": "Langsung cek akun @ownerarthaldtprodukviral dan @bunji.owner.artha untuk info lengkapnya!",
      "materi": [
        {
          "title": "Refrensi video",
          "url": "https://kontendotcom.b-cdn.net/materi/e8b663ee-bd3d-45b0-8113-a7b8fbc8081d/1784704883119-190ab118.mp4?token=7XAhd15ni9DMEjRK7bBcWBUfW0NVj0QaDAldcESBJAY&expires=1784706764"
        },
        {
          "title": "Materi slide 1",
          "url": "https://drive.google.com/drive/folders/18qzH3-_lnF9zJ3yUxeZcM94CnhSna6VD?usp=sharing"
        },
        {
          "title": "Materi slide 2",
          "url": "https://drive.google.com/drive/folders/1XRz-Kg0DZObdvoH7rYzwRDLuWqSK5fr0?usp=sharing"
        },
        {
          "title": "Materi slide 3",
          "url": "https://drive.google.com/drive/folders/1dk1OYPsVpG-6pHVz3aupuuF2hNfhrNTn?usp=sharing"
        },
        {
          "title": "Materi slide 4",
          "url": "https://drive.google.com/drive/folders/1xHwp2BUwEg77O3WFFPKRCcbkV6FMyA5_?usp=sharing"
        }
      ],
      "narasi": "- Mengajak audience untuk mencoba produk dari brand artha dan cek untuk akun arthaldtoffice\n- Membuat audience penasaran dengan produknya",
      "caption": "",
      "captionWajib": "Bodycare ini bener* ngasi bukti nyata 😍\n\nPOV: nyari bodycare yang gak PHP — dan ketemu ini 😭✨\nRating tinggi, testimoni nyata, kandungan lengkap. No menye-menye!\n\nInfo lengkap cek @ownerarthaldtprodukviral\n\n#arthaldt #bunjiownerartha #rekomendasibodycare #bodylotion #skincaretiktok",
      "hashtags": [
        "arthaldt",
        "arthaldtbpom",
        "bunjiownerartha",
        "testimoniartha"
      ],
      "durasiMin": "-",
      "durasiMax": "-",
      "judulFile": "BODYCARE ARTHA LDT",
      "elemenWajib": "Setiap carosel buat minimal 4 slide, wajib gunakan gambar/materi yang telah disediakan",
      "contohVideo": [],
      "tujuanCampaign": "Brand awareness: orang tahu brand/konten, Traffic: orang kunjungi website / profile / streaming page, Education: orang paham produk / topik, Sales: orang beli produk / buku / course",
      "targetAudiens": "13–17, 18–24, 25–34, 35–44",
      "instruksiBrief": "",
      "bolehDilakukan": [
        "- Gunakan materi dan testi sesuai brief",
        "- Gunakan materi sesuai dengan konten perslide yang disediakan",
        "- Masukan elemen text sebagai review produk nya",
        "- Refrensi text perslide bisa dicek di elemen clip yang disediakan"
      ],
      "dilarangDilakukan": [
        "- Dilarang ambil materi dari sumber lain",
        "- Jangan tambahkan text overlay klaim berlebihan",
        "- Jangan tambahkan filter yang mengubah warna produk / kulit drastis",
        "- Jangan bikin sentimen/komentar negatif ke brand/produk",
        "- Jaga kolom komentar, hapus komentar negatif yang bisa ngerusak citra brand",
        "- Larangan membandingkan dengan produk kompetitor.",
        "- Dilarang Screenshot materi campaign"
      ],
      "nicheAkunDisetujui": [
        "Lifestyle"
      ],
      "minimumFollowers": 0
    }
  }
];
