/**
 * Super Clipper — demo data generator.
 *
 * Reads the REAL crawl (research/konten-campaigns.json, produced by
 * scripts/crawl-campaigns.ts) and emits src/convex/demoData.ts: a curated set of
 * campaigns in the same shape konten.com returns, including the full
 * `brief_detail` (materi, narasi, CTA, elemen wajib, do & don'ts, target
 * audiens). This lets "Isi Data Demo" exercise the real brief parser offline.
 *
 * Big payloads (materi lists, narasi) are trimmed so the bundle stays small.
 * Personal data is never included — only campaign/brand fields.
 *
 * Run: bun scripts/crawl-campaigns.ts && bun scripts/gen-demo-data.ts
 */
import { readFileSync, writeFileSync } from "node:fs";

const SRC = "research/konten-campaigns.json";
const OUT = "src/convex/demoData.ts";

// Curated for breadth: film/brand awareness, education, podcast, F&B, beauty,
// gaming, and the IBU campaign the user briefed us with.
const PREFERRED = [
  "ibu-bagaimana-aku-tanpamu-trailer-soundtrack-film-copy",
  "david-noah-copy",
  "bevan",
  "podcast-wondermoms-community-vol-2-copy",
  "growlab-beyond-the-podcast-1",
  "owner-artha-ldt",
  "gapura-sariwangi",
  "mykonos-parfum",
  "sariwangi-dvc",
  "shinzui-sunscreen",
  "emina-fresh-drop-tint-2",
  "free-fire-x-naruto-shippuden",
  "bigbang-jakarta-sold-out-copy",
  "english-is-easy",
  "wardah-color-circuit",
  "cara-progress-lebih-cepat-dari-99-orang",
  "monster-hunter-outlanders",
  "tehpucuk-harum-less-sugar",
  "davidwijaya23-x-fyp-media",
  "bodycare-artha-ldt",
];

type Raw = Record<string, unknown>;
type Campaign = {
  slug: string;
  brief_detail?: Raw;
  [k: string]: unknown;
};

const file = JSON.parse(readFileSync(SRC, "utf8")) as { campaigns: Campaign[]; capturedAt: string };
const bySlug = new Map(file.campaigns.map((c) => [c.slug, c]));

const chosen: Campaign[] = [];
for (const s of PREFERRED) {
  const c = bySlug.get(s);
  if (c) chosen.push(c);
}
// Top up with the rest (richest briefs first) if fewer than 20 matched.
if (chosen.length < 20) {
  const rest = file.campaigns
    .filter((c) => !chosen.includes(c))
    .sort((a, b) => (b.brief_detail?.materi as unknown[] | undefined)?.length ?? 0 - ((a.brief_detail?.materi as unknown[] | undefined)?.length ?? 0));
  chosen.push(...rest.slice(0, 20 - chosen.length));
}

const str = (v: unknown, max: number): string => String(v ?? "").trim().slice(0, max);
const arr = (v: unknown, max: number): string[] =>
  (Array.isArray(v) ? v : []).map((x) => str(x, 200)).filter(Boolean).slice(0, max);

function slim(c: Campaign): Raw {
  const bd = (c.brief_detail ?? {}) as Raw;
  const materi = (Array.isArray(bd.materi) ? bd.materi : [])
    .map((m) => m as { title?: string; url?: string })
    .filter((m) => m?.url)
    .slice(0, 12)
    .map((m) => ({ title: str(m.title, 80), url: str(m.url, 400) }));

  return {
    id: str(c.id, 64),
    slug: str(c.slug, 120),
    title: str(c.title, 160),
    brand: str(c.brand, 80),
    category: str(c.category, 60),
    platform: arr(c.platform, 5),
    status: str(c.status, 24) || "active",
    campaign_type: str(c.campaign_type, 24) || "cpm",
    rate_per_million: c.rate_per_million ?? null,
    cpm_tiktok: c.cpm_tiktok ?? null,
    cpm_instagram: c.cpm_instagram ?? null,
    cpm_youtube: c.cpm_youtube ?? null,
    budget: c.budget ?? null,
    spent: c.spent ?? null,
    clippers: c.clippers ?? null,
    min_views: c.min_views ?? null,
    min_video_duration: c.min_video_duration ?? null,
    max_videos_per_clipper: c.max_videos_per_clipper ?? null,
    deadline: c.deadline ?? null,
    hashtags: arr(c.hashtags, 12),
    tier_access: str(c.tier_access, 24) || null,
    brief_detail: {
      cta: str(bd.cta, 400),
      materi,
      narasi: str(bd.narasi, 1500),
      caption: str(bd.caption, 600),
      captionWajib: str(bd.captionWajib, 600),
      hashtags: arr(bd.hashtags, 12),
      durasiMin: bd.durasiMin ?? null,
      durasiMax: bd.durasiMax ?? null,
      judulFile: str(bd.judulFile, 160),
      elemenWajib: str(bd.elemenWajib, 1500),
      contohVideo: [],
      tujuanCampaign: str(bd.tujuanCampaign, 300),
      targetAudiens: str(bd.targetAudiens, 120),
      instruksiBrief: str(bd.instruksiBrief, 800),
      bolehDilakukan: arr(bd.bolehDilakukan, 12),
      dilarangDilakukan: arr(bd.dilarangDilakukan, 12),
      nicheAkunDisetujui: arr(bd.nicheAkunDisetujui, 6),
      // API mengirim string untuk field numerik seperti ini — normalisasi ke angka.
      minimumFollowers: (() => {
        const n = Number(String(bd.minimumFollowers ?? "0").replace(/[^0-9]/g, ""));
        return Number.isFinite(n) ? n : 0;
      })(),
    },
  };
}

const slimmed = chosen.map(slim);
const header = `/* AUTO-GENERATED by scripts/gen-demo-data.ts — jangan edit manual.
 *
 * Sumber: crawl nyata konten.com ${file.capturedAt} (${file.campaigns.length} campaign tersedia,
 * ${slimmed.length} dipakai di sini). Berisi brief_detail asli: materi, narasi, CTA,
 * elemen wajib, do & don't, target audiens.
 *
 * Jalankan ulang: bun scripts/crawl-campaigns.ts && bun scripts/gen-demo-data.ts
 */
import type { RawCampaign } from "./lib/konten";

export const DEMO_CAPTURED_AT = ${JSON.stringify(file.capturedAt)};

export const DEMO_CAMPAIGNS: RawCampaign[] = `;

writeFileSync(OUT, header + JSON.stringify(slimmed, null, 2) + ";\n");

const totalMateri = slimmed.reduce((n, c) => n + ((c.brief_detail as Raw).materi as unknown[]).length, 0);
console.log(
  `[done] ${slimmed.length} campaigns, ${totalMateri} materi -> ${OUT} (${(JSON.stringify(slimmed).length / 1024).toFixed(0)} KB)`
);
